export const theme = {
  colorWhite: '#fff',
  colorBlack10: '#e6e6e6',
  colorBlack20: '#cccccc',
  colorGrey: '#8E9AAF',
  colorBeige05: '#f4fec1',
  colorPurple50: '#9067C6',
  colorPurple90: '#38182f',
  colorKhaki60: '#5c573e',
  colorCream20: '#f4fec1',
  colorOrangeRed: '#ff5917',

  IBMPlexSans100: 'IBMPlexSans-Thin',
  IBMPlexSans100Italic: 'IBMPlexSans-ThinItalic',
  IBMPlexSans200: 'IBMPlexSans-ExtraLight',
  IBMPlexSans200Italic: 'IBMPlexSans-ExtraLightItalic',
  IBMPlexSans300: 'IBMPlexSans-Light',
  IBMPlexSans300Italic: 'IBMPlexSans-LightItalic',
  IBMPlexSans400: 'IBMPlexSans-Regular',
  IBMPlexSans400Italic: 'IBMPlexSans-Italic',
  IBMPlexSans600: 'IBMPlexSans-SemiBold',
  IBMPlexSans600Italic: 'IBMPlexSans-SemiBoldItalic',
  IBMPlexSans700: 'IBMPlexSans-Bold',
  IBMPlexSans700Italic: 'IBMPlexSans-BoldItalic',

  IBMPlexMono100: 'IBMPlexMono-Thin',
  IBMPlexMono100Italic: 'IBMPlexMono-ThinItalic',
  IBMPlexMono200: 'IBMPlexMono-ExtraLight',
  IBMPlexMono200Italic: 'IBMPlexMono-ExtraLightItalic',
  IBMPlexMono300: 'IBMPlexMono-Light',
  IBMPlexMono300Italic: 'IBMPlexMono-LightItalic',
  IBMPlexMono400: 'IBMPlexMono-Regular',
  IBMPlexMono400Italic: 'IBMPlexMono-Italic',
  IBMPlexMono600: 'IBMPlexMono-SemiBold',
  IBMPlexMono600Italic: 'IBMPlexMono-SemiBoldItalic',
  IBMPlexMono700: 'IBMPlexMono-Bold',
  IBMPlexMono700Italic: 'IBMPlexMono-BoldItalic',
};
